"""initial schema

Revision ID: 685df3cb9303
Revises: 
Create Date: 2026-07-24 21:47:28.933916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '685df3cb9303'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login_id', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login_id')
    )
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('track_name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('preparing', 'active', 'closed', 'archived', name='seasonstatus', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('disqualified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('daily_count_override', sa.Integer(), nullable=True),
    sa.Column('daily_count_override_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'name', name='uq_team_season_name')
    )
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('login_id', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login_id'),
    sa.UniqueConstraint('team_id')
    )
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('model_path', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'done', 'error', name='submissionstatus', native_enum=False, length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('worker_id', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_team_active_submission', 'submissions', ['team_id'], unique=True, postgresql_where=sa.text("status IN ('queued', 'running')"))
    op.create_table('evaluation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('finish_status', sa.Enum('finished', 'timeout', name='finishstatus', native_enum=False, length=20), nullable=False),
    sa.Column('lap_time_seconds', sa.Float(), nullable=True),
    sa.Column('off_track_count', sa.Integer(), nullable=False),
    sa.Column('video_path', sa.String(length=500), nullable=True),
    sa.Column('metrics_raw_path', sa.String(length=500), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluation_results')
    op.drop_index('uq_team_active_submission', table_name='submissions', postgresql_where=sa.text("status IN ('queued', 'running')"))
    op.drop_table('submissions')
    op.drop_table('accounts')
    op.drop_table('teams')
    op.drop_table('seasons')
    op.drop_table('admin_accounts')
    # ### end Alembic commands ###
